### ISSUE TITLE
Missing link to DUB's google calendar

### ISSUE THREAD

**Issue by kanitw** [uwdub/web-dub#257] opened 2016-06-22 17:11 UTC
I can't find the link on this page http://dub.uw.edu/calendar.html :)

**Comment by depstein** [comment] 2016-06-22 18:12
Here's my understanding: We're currently maintaining two versions of the
calendar: one on the website, another on the google calendar. Someone has
been working on auto-populating an ICS based on the website content, which
should be launched soon. But we don't want a whole bunch of people
subscribing to a google calendar which will be deprecated in a few months
:-)

~Daniel Epstein

**Comment by kanitw** [comment] 2016-06-22 18:29
Oh I see.

**Comment by jayfo** [comment] 2016-06-28 20:15
We do indeed have an ICS file we're publishing here:

http://dub.washington.edu/calendar.ics

It's driven from the same data that populates the DUB website seminar pages. The calendar file isn't perfect yet, but we could help it along if that became a priority.

One blocker here is making it easy for people to add the calendar. Does anybody know how we can make a "add this calendar to my calendar" sort of link?

**Comment by smunson** [comment] 2016-10-14 18:24
It's annoying -- most browsers default to downloading the ICS file, and so most of the instructions say stuff like "copy the link, then go to your calendar" or write some JS that pops up a dialog that tells people to copy the link.

**Comment by jayfo** [comment] 2016-12-30 20:15
The above calendar file is now being generated more properly.  The issue is now whether there's any 'nice' way to support people in adding that link to their personal calendars. I've previously posted this in a different issue:

> The Google subscribe link seems to be:
>
> https://calendar.google.com/calendar/render?cid={{ http_path_to_ics_file }}
> 
> It also seems like maybe this is a thing:
> 
> webcal://{{ path_to_ics_file }}

**Comment by smunson** [comment] 2017-04-04 22:25
I think if we provide some text on the calendar page, we can probably close this issue? No one has complained to me about the switch.

**Comment by depstein** [comment] 2017-04-04 22:35
This is resolved in pull request #347. But it hasn't been merged yet, hence this issue staying open.

**Comment by jayfo** [comment] 2017-08-20 18:37
Fixed in #347.

**Closed by jayfo** 2017-08-20 18:37 UTC
